import type { NodeDefinition } from "@/types/workflow"
import type { LucideIcon } from "lucide-react"
import {
  Globe,
  Clock,
  FolderUp,
  Radio,
  Mail,
  MessageSquare,
  Bell,
  Smartphone,
  MessageCircle,
  Users,
  Webhook,
  TestTube,
  GitBranch,
  Shuffle,
  Repeat,
  Timer,
  GitMerge,
  Map as MapIcon,
  Filter,
  Settings,
  FileText,
  Hourglass,
} from "lucide-react"

// Icon mapping for each node type
export const NODE_ICONS: Record<string, LucideIcon> = {
  "api-trigger": Globe,
  "schedule-trigger": Clock,
  "file-trigger": FolderUp,
  "event-trigger": Radio,
  "send-email": Mail,
  "send-sms": MessageSquare,
  "send-push": Bell,
  "send-in-app": Smartphone,
  "send-slack": MessageCircle,
  "send-discord": MessageCircle,
  "send-teams": Users,
  "send-webhook": Webhook,
  "ab-test": TestTube,
  "condition": GitBranch,
  "switch": Shuffle,
  "loop": Repeat,
  "delay": Timer,
  "merge": GitMerge,
  "map": MapIcon,
  "filter": Filter,
  "transform": Settings,
  "read-file": FileText,
  "wait-events": Hourglass,
}

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // Trigger Nodes - Blue (#0ea5e9)
  {
    type: "api-trigger",
    category: "trigger",
    label: "API Trigger",
    description: "Starts workflow on HTTP request",
    icon: "api-trigger",
    color: "#0ea5e9",
    inputs: 0,
    outputs: 1,
  },
  {
    type: "schedule-trigger",
    category: "trigger",
    label: "Schedule Trigger",
    description: "Starts workflow on schedule",
    icon: "schedule-trigger",
    color: "#0ea5e9",
    inputs: 0,
    outputs: 1,
  },
  {
    type: "file-trigger",
    category: "trigger",
    label: "File Upload",
    description: "Starts workflow on file upload",
    icon: "file-trigger",
    color: "#0ea5e9",
    inputs: 0,
    outputs: 1,
  },
  {
    type: "event-trigger",
    category: "trigger",
    label: "Event Trigger",
    description: "Starts workflow on event",
    icon: "event-trigger",
    color: "#0ea5e9",
    inputs: 0,
    outputs: 1,
  },
  // Action Nodes - Green (#22c55e)
  {
    type: "send-email",
    category: "action",
    label: "Send Email",
    description: "Send email notification",
    icon: "send-email",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-sms",
    category: "action",
    label: "Send SMS",
    description: "Send SMS notification",
    icon: "send-sms",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-push",
    category: "action",
    label: "Send Push",
    description: "Send push notification",
    icon: "send-push",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-in-app",
    category: "action",
    label: "Send In-App",
    description: "Send in-app notification",
    icon: "send-in-app",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-slack",
    category: "action",
    label: "Send Slack",
    description: "Send Slack message",
    icon: "send-slack",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-discord",
    category: "action",
    label: "Send Discord",
    description: "Send Discord message",
    icon: "send-discord",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-teams",
    category: "action",
    label: "Send Teams",
    description: "Send Teams message",
    icon: "send-teams",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send-webhook",
    category: "action",
    label: "Send Webhook",
    description: "Send webhook request",
    icon: "send-webhook",
    color: "#22c55e",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "ab-test",
    category: "logic",
    label: "A/B Test",
    description: "Split traffic between variants",
    icon: "ab-test",
    color: "#f59e0b",
    inputs: 1,
    outputs: 2,
  },
  // Logic Nodes - Amber (#f59e0b)
  {
    type: "condition",
    category: "logic",
    label: "Condition",
    description: "If/Then/Else branching",
    icon: "condition",
    color: "#f59e0b",
    inputs: 1,
    outputs: 2,
  },
  {
    type: "switch",
    category: "logic",
    label: "Switch",
    description: "Multi-case branching",
    icon: "switch",
    color: "#f59e0b",
    inputs: 1,
    outputs: 3,
  },
  {
    type: "loop",
    category: "logic",
    label: "Loop",
    description: "Iterate over array",
    icon: "loop",
    color: "#f59e0b",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "delay",
    category: "logic",
    label: "Delay",
    description: "Wait for specified time",
    icon: "delay",
    color: "#f59e0b",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "merge",
    category: "logic",
    label: "Merge",
    description: "Combine multiple branches",
    icon: "merge",
    color: "#f59e0b",
    inputs: 2,
    outputs: 1,
  },
  // Data Nodes - Purple (#8b5cf6)
  {
    type: "map",
    category: "data",
    label: "Map",
    description: "Transform data structure",
    icon: "map",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "filter",
    category: "data",
    label: "Filter",
    description: "Filter array based on condition",
    icon: "filter",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "transform",
    category: "data",
    label: "Transform",
    description: "Custom data transformation",
    icon: "transform",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
  },
  {
    type: "read-file",
    category: "data",
    label: "Read File",
    description: "Parse uploaded file",
    icon: "read-file",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
  },
  // Integration Nodes - Teal (#14b8a6)
  {
    type: "wait-events",
    category: "logic",
    label: "Wait for Events",
    description: "Wait for API response and/or Kafka event",
    icon: "wait-events",
    color: "#14b8a6",
    inputs: 1,
    outputs: 1,
  },
]

export const NODES_BY_CATEGORY = {
  trigger: NODE_DEFINITIONS.filter((n) => n.category === "trigger"),
  action: NODE_DEFINITIONS.filter((n) => n.category === "action"),
  logic: NODE_DEFINITIONS.filter((n) => n.category === "logic"),
  data: NODE_DEFINITIONS.filter((n) => n.category === "data"),
}

